### ISSUE TITLE
About Coupled Temperature-Displacement analysis type

### ISSUE THREAD

**Issue by Ttw0626** [FrontISTR/FrontISTR#11]
Dear tech. support of FrontISTR,

Good afternoon, here is TAN.

I wanna try to implement the coupled temp-disp analysis within FrontISTR,
however, the heat transfer and Static or Quasi-Static are individual right now
if I am not wrong.
 
it will spend a lot of time to totally comprehend the source codes.
(the new coupled element, the new time stepping involving the (nonlinear) load stepping,
{most difficult} the info. communication interface within two processes and so on....)

Could you give me some suggestions about this ?

Thanks so much.

Best regards,
TAN

**Comment by kinagaki** [comment]
Dear TAN,

To perform a coupled temperature-displacement analysis within FrontISTR, you can utilize the !TEMPERATURE,READRESULT command. Detailed information about this data block can be found in the manual at the following link:
https://manual.frontistr.com/en/analysis/analysis_05.html#20-temperature-2-9

By specifying thermal loads using !TEMPERATURE,READRESULT in the deformation stress analysis control file, you can obtain the temperature distribution from the heat conduction analysis result file and calculate the thermal strain based on that temperature distribution. Here's how to use it:

Perform heat conduction analysis. Make sure the result file is output with !WRITE,RESULT.
Perform deformation stress analysis. Follow these steps during execution:
a. Use the same mesh as in the heat conduction analysis. If you have divided the domain, use the split mesh as-is.
b. Add the following data block to the hecmw_ctrl.dat of the deformation stress analysis to reference the temperature distribution of the heat conduction analysis.
c. Specify !TEMPERATURE,READRESULT in the deformation stress analysis control file.
Example for step 2b:
!RESULT, NAME=fstrTEMP
heat_analysis.res

Example for step 2c (for a heat conduction analysis with a single time step):
!TEMPERATURE,READRESULT=1,SSTEP=1,INTERVAL=1,READTYPE=STEP

I hope this helps. If you have any further questions, please feel free to ask.

Best regards,

**Comment by Ttw0626** [comment]
Dear Kinagaki-san,

Good morning, Here is Tan, Thanks for your reply and help.

I am attempting and implementing it.

Thanks again, I will close this Q&A.

Best regards,
TAN
