### ISSUE TITLE
Failed to compile tools

### ISSUE THREAD

**Issue by RATATATO** [FrontISTR/FrontISTR#2]
# Description
I failed to compile while tool compiles with the follow message.

```
[ 49%] Building C object hecmw1/tools/CMakeFiles/hec2rcap.dir/hec2rcap/hec2rcap.c.o
Linking CXX executable hec2rcap
/usr/bin/ld: cannot open output file hec2rcap: Is a directory

...
Linking CXX executable neu2fstr
/usr/bin/ld: cannot open output file neu2fstr: Is a directory
```

# Steps
1. Check out from this repository.
2. Run the follow command.

```
cmake .
make
```

# Possible Implementation
It seems to cause this for that the source directory name and the binary name were same, and CMake confused its.

So I suggest to
1. rename hec2rcap and neu2fstr, or
3. output the binary to the other directory like bin.

# Environment
CentOS 6

**Comment by nqomorita** [comment]
Thank you for opening this issue!

# Recommended Steps

1. Check out from this repository.
1. Run the follow command. We assumed that FrontISTR is compiled with out-of-source build.

```
mkdir build
cd build
cmake ..
make
```

# Correction

When we try to compile with in-source build, cmake outputs an error and commands urging to do with out-of-source build. This correction is already committed in the latest master branch.

**Comment by RATATATO** [comment]
I tried https://github.com/FrontISTR/FrontISTR/issues/2#issuecomment-379312362 , and I succeed to compile this.
Thank you for the reply and I close this issue.

But though CMake recommends out-of-source build, in-source build has been common yet.
Please consider this if you fix this easily.
